# Generated by Django 4.2.7 on 2023-12-16 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0021_merge_20231211_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='NixDerivationAffectedView',
            fields=[
                ('id', models.ForeignKey(db_column='drv_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='shared.nixderivation')),
                ('attribute', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('issue_code', models.CharField(max_length=255)),
                ('issue_status', models.CharField(choices=[('U', 'unknown'), ('A', 'affected'), ('NA', 'notaffected'), ('O', 'notforus'), ('W', 'wontfix')], default='U', max_length=2)),
                ('cve_code', models.CharField(max_length=255)),
                ('cve_state', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('REJECTED', 'REJECTED')], default='PUBLISHED', max_length=9)),
                ('channel_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shared_affected_derivation',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE VIEW shared_affected_derivation AS
                SELECT eval.channel_id,
                drv.id AS drv_id,
                drv.attribute AS attribute,
                drv.derivation_path  AS path,
                issue.id AS issue_id,
                issue.code AS issue_code,
                issue.status AS issue_status,
                cve.id AS cve_id,
                cve.cve_id AS cve_code,
                cve.state AS cve_state
                -- meta.known_vulnerabilities -- confirm that it's only used during ingestion
            FROM shared_nixpkgsissue issue INNER JOIN
                shared_nixpkgsissue_cve icve
                ON issue.id = icve.nixpkgsissue_id INNER JOIN
                shared_nixpkgsissue_derivations idrv
                ON issue.id = idrv.nixpkgsissue_id INNER JOIN
                shared_cverecord cve
                ON cve.id = icve.cverecord_id INNER JOIN
                shared_nixderivation drv
                ON drv.id = idrv.nixderivation_id INNER JOIN
                shared_nixevaluation eval
                ON drv.parent_evaluation_id = eval.id INNER JOIN
                shared_nixderivationmeta meta
                ON drv.metadata_id = meta.id
            WHERE issue.status = 'A';
            """,
            """
            DROP VIEW shared_affected_derivation;
            """
        ),
    ]
