# Generated by Django 4.2.7 on 2024-09-03 10:26

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0006_delete_aggregateevent'),
        ('shared', '0029_merge_20240809_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='NixpkgsIssueAggregatedLog',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=None, null=True)),
                ('table', models.CharField(max_length=256)),
                ('changes', models.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NixpkgsIssueCveLog',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NixpkgsIssueDerivationLog',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NixpkgsIssueLog',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('status', models.CharField(choices=[('U', 'unknown'), ('A', 'affected'), ('NA', 'notaffected'), ('O', 'notforus'), ('W', 'wontfix')], default='U', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NixpkgsIssueCveProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shared.nixpkgsissue_cve',),
        ),
        migrations.CreateModel(
            name='NixpkgsIssueDerivationProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shared.nixpkgsissue_derivations',),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsissue',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "shared_nixpkgsissuelog" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (_pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status"); RETURN NULL;', hash='8002f5bc33eb552273a9f75cc973fec1db546fb1', operation='INSERT', pgid='pgtrigger_insert_insert_9d8a7', table='shared_nixpkgsissue', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsissue',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "shared_nixpkgsissuelog" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (_pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status"); RETURN NULL;', hash='ee77b626a75eda1a7e7cb0285018a2ef2084e146', operation='UPDATE', pgid='pgtrigger_update_update_8088b', table='shared_nixpkgsissue', when='AFTER')),
        ),
        migrations.AddField(
            model_name='nixpkgsissuelog',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='nixpkgsissuelog',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_events', to='shared.nixpkgsissue'),
        ),
        migrations.AddField(
            model_name='nixpkgsissuederivationlog',
            name='nixderivation',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shared.nixderivation'),
        ),
        migrations.AddField(
            model_name='nixpkgsissuederivationlog',
            name='nixpkgsissue',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shared.nixpkgsissue'),
        ),
        migrations.AddField(
            model_name='nixpkgsissuederivationlog',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='nixpkgsissuederivationlog',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='shared.nixpkgsissuederivationproxy'),
        ),
        migrations.AddField(
            model_name='nixpkgsissuecvelog',
            name='cverecord',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shared.cverecord'),
        ),
        migrations.AddField(
            model_name='nixpkgsissuecvelog',
            name='nixpkgsissue',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shared.nixpkgsissue'),
        ),
        migrations.AddField(
            model_name='nixpkgsissuecvelog',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='nixpkgsissuecvelog',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='shared.nixpkgsissuecveproxy'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsissuecveproxy',
            trigger=pgtrigger.compiler.Trigger(name='cve_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "shared_nixpkgsissuecvelog" ("cverecord_id", "id", "nixpkgsissue_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cverecord_id", NEW."id", NEW."nixpkgsissue_id", _pgh_attach_context(), NOW(), \'cve.add\', NEW."id"); RETURN NULL;', hash='c89ca48cbbb79aefcfa63fcf7b10fb2baa84a886', operation='INSERT', pgid='pgtrigger_cve_add_insert_22b8c', table='shared_nixpkgsissue_cve', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsissuecveproxy',
            trigger=pgtrigger.compiler.Trigger(name='cve_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "shared_nixpkgsissuecvelog" ("cverecord_id", "id", "nixpkgsissue_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."cverecord_id", OLD."id", OLD."nixpkgsissue_id", _pgh_attach_context(), NOW(), \'cve.remove\', OLD."id"); RETURN NULL;', hash='e596a0c6a91c08203a9e1f27de6bf963546ac61f', operation='DELETE', pgid='pgtrigger_cve_remove_delete_26b78', table='shared_nixpkgsissue_cve', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsissuederivationproxy',
            trigger=pgtrigger.compiler.Trigger(name='derivations_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "shared_nixpkgsissuederivationlog" ("id", "nixderivation_id", "nixpkgsissue_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."nixderivation_id", NEW."nixpkgsissue_id", _pgh_attach_context(), NOW(), \'derivations.add\', NEW."id"); RETURN NULL;', hash='e17d5c1f7dabf4300ab88740dadec3abd43c61f0', operation='INSERT', pgid='pgtrigger_derivations_add_insert_5cfcd', table='shared_nixpkgsissue_derivations', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsissuederivationproxy',
            trigger=pgtrigger.compiler.Trigger(name='derivations_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "shared_nixpkgsissuederivationlog" ("id", "nixderivation_id", "nixpkgsissue_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."id", OLD."nixderivation_id", OLD."nixpkgsissue_id", _pgh_attach_context(), NOW(), \'derivations.remove\', OLD."id"); RETURN NULL;', hash='546c41faa50576a9f4a2587d3579799d4d101b70', operation='DELETE', pgid='pgtrigger_derivations_remove_delete_f136b', table='shared_nixpkgsissue_derivations', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsissuelog',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='bd2252f3dd072bd1cea269c9c6294651286b6df4', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_28850', table='shared_nixpkgsissuelog', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsissuederivationlog',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='5e17e0a897d1ed7f618fd339ef77127b3bc273e1', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_68419', table='shared_nixpkgsissuederivationlog', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsissuecvelog',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='64f1c91b9a65ca44ccd7a7fbc00071a73cfed1dd', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_39252', table='shared_nixpkgsissuecvelog', when='BEFORE')),
        ),
    ]
