# Generated by Django 4.2.7 on 2024-09-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0030_nixpkgsissueaggregatedlog_nixpkgsissuecvelog_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nixpkgsissueaggregatedlog',
            table='pghistory_context',
        ),
    ]
